### ISSUE TITLE
Link Issue with Restkit

### ISSUE THREAD

**Issue by savage7** [passslot/passslot-ios-sdk#1]
When you build it with restkit:
duplicate symbol _NewBase64Decode in:
    Libraries/passslot/sdk/PassSlot.framework/PassSlot(NSData+Base64.o)
    /Build/Products/Debug-iphonesimulator/libRestKit.a(NSData+Base64.o)
duplicate symbol _NewBase64Encode in:
    Libraries/passslot/sdk/PassSlot.framework/PassSlot(NSData+Base64.o)
    /Build/Products/Debug-iphonesimulator/libRestKit.a(NSData+Base64.o)
ld: 2 duplicate symbols for architecture i386

**Comment by passslot** [comment]
Hi savage7

Thank you for reporting this issue. We will soon release an updated version of the SDK that resolves your problem. 
Please contact us at support@passslot.com if you need the updated version as soon as possible and don't want to wait for the next release.

**Comment by passslot** [comment]
Hi savage7

In PassSlot SDK v0.4 this issue is resolved, we could successfully link PassSlot with RestKit.
