### ISSUE TITLE
64-bit Support

### ISSUE THREAD

**Issue by Sam-Spencer** [passslot/passslot-ios-sdk#2]
Could you add 64-bit support for iOS devices with the 64-bit Apple A7 processor? It would only require adding the `arm64` architecture to your build settings and then repairing any warnings. Any estimate on when this will be ready?

**Comment by lfarah** [comment]
having this issue too!

**Comment by passslot** [comment]
we have a beta version which has this issue fixed. 
please contact support@passslot.com to get pre release access

**Comment by passslot** [comment]
it may look that simple, but in fact it is not. upgrading to 64 bit is not just changing a flag in the build settings. we need to make sure that all used code is 64 bit compatible and that there are no other problems. that's also why we do beta test our SDK before we release it into the wild.

You are right that we could have released the new SDK already some months ago, but given the fact that you are not forced to use 64 bit, this was only low priority.

We have now released version 0.7 of the SDK
