### ISSUE TITLE
Error building on Device - Linker command failed with exit code 1

### ISSUE THREAD

**Issue by AlexHedley** [passslot/passslot-ios-sdk#4]
I created a new project and used cocoapods to install `'PassSlot'`

Added my API Key and can call `createPassFromTemplateWithName` within the Simulator.

When I try and build for a device I'm getting the following error:

> Apple Mach-O Linker (ld) Error Group
> clang: error: Linker command failed with exit code 1 (use -v to see invocation)

I'm opening the `.xcworkspace` and not the `.xcodeproj`
I've tried a clean and fresh build.
I've tried deleting DerivedData.
I've rebooted Xcode.

Any other suggestions?

**Comment by passslot** [comment]
Hi

We would have to know more about the details of the error. Could you share your error log?

Best regards

**Comment by AlexHedley** [comment]
Completely missed this:

> ld: 'PROJECT/Pods/PassSlot/sdk/PassSlot.framework/PassSlot(PSImage.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Target | Build Settings
Enable Bitcode - No 'Change from Yes

**Comment by passslot** [comment]
Hi 

Did it work after you have disabled bitcode?

Best regards

**Comment by AlexHedley** [comment]
It did indeed, sorry thought I'd implied, happy to close the issue. :)

Would it be worth adding it to the Readme?

**Comment by passslot** [comment]
We will see that we can add Bitcode to the next release

**Comment by AlexHedley** [comment]
Thanks :)
